- name: "Install pwgen"
  apt:
    name: "pwgen"
    state: present
    install_recommends: no
  tags:
    - packages
    - tripwire

- name: "Check that the site password file exists"
  stat: path="/root/.sitekey.tripwire"
  register: site_result
  tags:
    - tripwire

- name: "Check that the site password file exists"
  stat: path="/root/.localkey.tripwire"
  register: local_result
  tags:
    - tripwire

- name: "Generate a site password for tripwire"
  shell: pwgen 32 1 > /root/.sitekey.tripwire
  when: not site_result.stat.exists
  tags: 
    - tripwire

- name: "Generate a local password for tripwire"
  shell: pwgen 32 1 > /root/.localkey.tripwire
  when: not local_result.stat.exists
  tags:
    - tripwire

- name: "Register Site Key variable"
  shell: cat /root/.sitekey.tripwire
  register: tripwire_sitekey
  tags:
    - tripwire

- name: "Register local key variable"
  shell: cat /root/.localkey.tripwire
  register: tripwire_localkey
  tags:
    - tripwire

- name: "Install tripwire"
  apt:
    name: "tripwire"
    state: present
    install_recommends: no
  tags:
    - packages
    - tripwire

- name: "Remove auto created local key"
  file: 
    path: "{{ tripwire_config_dir }}/{{ ansible_hostname }}-local.key"
    state: absent
  tags:
    - tripwire

- name: "Remove auto created site key"
  file: 
    path: "{{ tripwire_config_dir }}/site.key"
    state: absent
  tags:
    - tripwire

- name: "Generate Tripwire Host Key"
  command: twadmin --generate-keys --local-keyfile "{{ tripwire_config_dir }}/{{ ansible_hostname }}-local.key" --local-passphrase "{{ tripwire_localkey.stdout }}"
  tags:
   - tripwire

- name: "Generate Tripwire Site Key"
  command: twadmin --generate-keys --site-keyfile "{{ tripwire_config_dir }}/site.key" --site-passphrase  "{{ tripwire_sitekey.stdout }}"
  tags:
    - tripwire

- name: "Deploy our customised policy"
  template:
    src: etc/tripwire/twpol.txt
    dest: /etc/tripwire/twpol.txt
    owner: root
    group: root
    mode: 0644
  tags:
    - tripwire

- name: "Deploy our customised configuraton"
  template:
    src: etc/tripwire/twcfg.txt
    dest: /etc/tripwire/twcfg.txt
    owner: root
    group: root
    mode: 0644
  tags:
    - tripwire

- name: "Encrypt Tripwire Configuration"
  command: twadmin --create-cfgfile --site-keyfile "{{ tripwire_config_dir }}/site.key" --site-passphrase  "{{ tripwire_sitekey.stdout }}" "{{ tripwire_config_dir }}/twcfg.txt"
  tags:
   - tripwire

- name: "Encrypt Tripwire Policy"
  command: twadmin --create-polfile --site-passphrase "{{ tripwire_sitekey.stdout }}" "{{ tripwire_config_dir }}/twpol.txt"
  tags:
   - tripwire

- name: "Tripwire Initial Database"
  shell: tripwire --init -P "{{ tripwire_localkey.stdout }}"
  tags:
    - tripwire

